### ISSUE TITLE
A Note On Portfolio Credit Risk Modeling · Rongjia Liu

### ISSUE THREAD

**Issue by jackliu234** [jackliu234/jackliu234.github.io#6]
https://jackliu234.com/2019-02-14/ 

 A Note On Portfolio Credit Risk Modeling - Rongjia Liu

**Comment by allenfrostline** [comment]
观光打卡（beep

**Comment by jackliu234** [comment]
学到痴狂了
> @allenfrostline
> 观光打卡（beep
